apiVersion: apps/v1
kind: Statefulset
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          ports:
          {{- range .Values.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
          {{- end }}
          readinessProbe:
            failureThreshold: {{ .Values.probe.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.probe.readinessProbe.httpGet.path }}
              port: {{ .Values.probe.readinessProbe.httpGet.port }}
              scheme: {{ .Values.probe.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.probe.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.probe.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.probe.readinessProbe.timeoutSeconds }}
          livenessProbe:
            failureThreshold: {{ .Values.probe.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.probe.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.probe.livenessProbe.successThreshold }}
            tcpSocket:
              port: {{ .Values.probe.livenessProbe.tcpSocket.port }}
            timeoutSeconds: {{ .Values.probe.livenessProbe.timeoutSeconds }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          volumeMounts:
          {{- range .Values.volumeMounts }}
            - mountPath: {{ .mountPath }}
              name: {{ .name }}
          {{- end }}
      volumes:
      {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
      {{- end }}