replicas: 1

stage: dev

image:
  repository: europe-west1-docker.pkg.dev/wp-project-manage/wp-project-infra-registry/wp-image

envFromSecrets:
  mysql:
    WORDPRESS_DB_HOST: db_host
    WORDPRESS_DB_NAME: db_name
    WORDPRESS_DB_USER: db_username
    WORDPRESS_DB_PASSWORD: db_password

volumeMounts:
  - name: wordpress-content
    mountPath: /var/www/html/wp-content

volumes:
  - name: wordpress-content
    persistentVolumeClaim:
      claimName: wordpress-pvc

service:
  type: LoadBalancer
  loadBalancerIP: 34.22.250.29
  ports:
    - name: http
      port: 80
      targetPort: 80