replicas: 1

stage: dev

image:
  repository: europe-west1-docker.pkg.dev/wp-project-manage/aspnet-project-infra-registry/aspnet-image

resources:
  requests:
    memory: 500Mi
    cpu: 200m
  limits:
    memory: 1Gi
    cpu: 500m

volumes:
  - name: aspnet-content
    persistentVolumeClaim:
      claimName: aspnet-pvc

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80