replicas: 1

stage: production

image:
  repository: europe-west1-docker.pkg.dev/wp-project-manage/aspnet-project-infra-registry/aspnet-image

resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 200Mi
    cpu: 100m

volumeMounts:
  - name: wordpress-content
    mountPath: /var/www/html/wp-content

volumes:
  - name: wordpress-content
    persistentVolumeClaim:
      claimName: wordpress-pvc

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80