replicas: 1

stage: qa

image:
  repository: europe-west1-docker.pkg.dev/wp-project-manage/aspnet-project-infra-registry/aspnet-image

volumes:
  - name: aspnet-content
    persistentVolumeClaim:
      claimName: aspnet-pvc

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80