replicas: 1

image:
  repository: grafana/grafana:latest

ports:
  - containerPort: 3000
    name: http-grafana
    protocol: TCP

resources:
  requests:
    cpu: 250m
    memory: 750Mi
  limits:
    cpu: 400m
    memory: 1Gi

probe:
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /robots.txt
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 10
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 2
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 3000
    timeoutSeconds: 1

volumeMounts:
  - mountPath: /var/lib/grafana
    name: grafana-pv
volumes:
  - name: grafana-pv
    persistentVolumeClaim:
      claimName: grafana-pvc

service:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana