apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      helm.sh/chart: {{ .Chart.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
      {{- include "labels" . | nindent 4 }}
    spec:
      imagePullSecrets:
      - name: registry-sa
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.stage }}
          imagePullPolicy: Always
          env:
          {{- range $secretName, $secretData := .Values.envFromSecrets }}
          {{- range $secretEnvName, $secretEnvValue := $secretData }}
            - name: {{ $secretEnvName }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $secretEnvValue }}
          {{- end }}
          {{- end }}
          volumeMounts: {{ toYaml .Values.volumeMounts | default "" | nindent 12 }}
      volumes: {{ toYaml .Values.volumes | default "" | nindent 6 }}