apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "labels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 4 }}
    spec:
      imagePullSecrets:
      - name: registry-sa
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.stage }}
          imagePullPolicy: Always
          volumeMounts: {{ toYaml .Values.volumeMounts | default "" | nindent 12 }}
      volumes: {{ toYaml .Values.volumes | default "" | nindent 6 }}