apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      helm.sh/chart: {{ .Chart.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      imagePullSecrets:
      - name: registry-sa
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.stage }}
          imagePullPolicy: Always
          volumeMounts: {{ toYaml .Values.volumeMounts | default "" | nindent 12 }}
      volumes: {{ toYaml .Values.volumes | default "" | nindent 6 }}