apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Chart.name }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.name }}-pvc
  namespace: aspnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "gce-provision"