name: Helm package and push

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "enter service"
        default: ""
        type: "string"

jobs:
  make-chart-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        env:
          environment: "dev"
        run: |-
          pushd charts/${{ inputs.service_name }}
          sed -i s/${{ inputs.service_name }}/${{ inputs.service_name }}-${{ env.environment }}/g Chart.yaml
          mv values-${{ env.environment }}.yaml values.yaml
          ls -al
          popd
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
  make-chart-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        env:
          environment: "qa"
        run: |-
          pushd charts/${{ inputs.service_name }}
          sed -i s/${{ inputs.service_name }}/${{ inputs.service_name }}-${{ env.environment }}/g Chart.yaml
          mv values-${{ env.environment }}.yaml values.yaml
          ls -al
          popd
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts