name: Helm package and push for QA-test

on:
  workflow_dispatch:
    inputs:
      aspnet:
        type: boolean
        description: Check to build the helm chart for aspnet
        required: false
        default: "false"
      wordpress:
        type: boolean
        description: Check to build the helm chart for wordpress
        required: false
        default: "false"

env:
  ENVIRONMENT: "qa"
  REPO_URL: "https://pcladiu97.github.io/helm-repos/"

jobs:
  helm-chart-aspnet-qa:
    if: ${{ inputs.aspnet }}
    env:
      SERVICE_NAME: aspnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Helm package
        run: |-
          pushd charts/${{ env.SERVICE_NAME }} 
          sed -i s/_CHART_NAME_/${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}/g Chart.yaml
          mv values-${{ env.ENVIRONMENT }}.yaml values.yaml
          popd 
          helm package charts/${{ env.SERVICE_NAME }} && helm repo index .
          helm plugin install https://github.com/chartmuseum/helm-push
          helm repo add helm-repos ${{ env.REPO_URL }}
          helm repo update
          helm cm-push ${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}*.tgz helm-repos
  helm-chart-wordpress-qa:
    if: ${{ inputs.wordpress }}
    env:
      SERVICE_NAME: wordpress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Helm package
        run: |-
          pushd charts/${{ env.SERVICE_NAME }} 
          sed -i s/_CHART_NAME_/${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}/g Chart.yaml
          mv values-${{ env.ENVIRONMENT }}.yaml values.yaml
          popd 
          helm package charts/${{ env.SERVICE_NAME }} && helm repo index .
          helm repo add helm-repos ${{ env.REPO_URL }}
          helm repo update
          helm push ${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}*.tgz helm-repos