name: Helm package and push for QA-test

on:
  workflow_dispatch:
    inputs:
      aspnet:
        type: boolean
        description: Check to build the helm chart for aspnet
        required: false
        default: "false"
      wordpress:
        type: boolean
        description: Check to build the helm chart for wordpress
        required: false
        default: "false"

env:
  ENVIRONMENT: "qa"

jobs:
  helm-chart-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set variables aspnet
        if: ${{ github.event.inputs.aspnet == true }}
        env:
          SERVICE_NAME: "aspnet"
        run: echo ${{ env.SERVICE_NAME }}
      - name: Set variables wordpress
        if: ${{ github.event.inputs.aspnet == true }}
        env:
          SERVICE_NAME: "wordpress"
        run: echo ${{ env.SERVICE_NAME }}
      - name: Helm package
        run: |-
          ls -al
          pushd charts/${{ env.SERVICE_NAME }} 
          sed -i s/_CHART_NAME_/${{ env.SERVICE_NAME }}-${{ env.ENVIRONMENT }}/g Chart.yaml
          mv values-${{ env.ENVIRONMENT }}.yaml values.yaml
          ls -al
          popd 
          helm package charts/${{ env.SERVICE_NAME }} && helm repo index .