name: Helm package and push for QA

on:
  workflow_dispatch:
    inputs:
      aspnet:
        type: boolean
        description: Check to build the helm chart for aspnet
      wordpress:
        type: boolean
        description: Check to build the helm chart for wordpress

env:
  ENVIRONMENT: "qa"

jobs:
  helm-chart-aspnet-qa:
    if: ${{ github.event.inputs.aspnet }}
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "aspnet"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        run: |-
          find . ! -name ${{ env.SERVICE_NAME }} -type d -exec rm -rf {} +
          pushd charts/${{ env.SERVICE_NAME }} 
          sed -i s/${{ env.SERVICE_NAME }}  /${{ env.SERVICE_NAME }} -${{ env.ENVIRONMENT }}/g Chart.yaml
          mv values-${{ env.ENVIRONMENT }}.yaml values.yaml
          ls -al
          popd 
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts/${{ env.SERVICE_NAME }}
  helm-chart-wordpress-qa:
    if: ${{ github.event.inputs.wordpress }}
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "wordpress"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        run: |-
          pushd charts/${{ env.SERVICE_NAME }} 
          sed -i s/${{ env.SERVICE_NAME }}  /${{ env.SERVICE_NAME }} -${{ env.ENVIRONMENT }}/g Chart.yaml
          mv values-${{ env.ENVIRONMENT }}.yaml values.yaml
          ls -al
          popd 
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts/${{ env.SERVICE_NAME }}  