name: Helm package and push

on: workflow_dispatch

env:
  environment: "null"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        env:
          environment: "dev"
        run: |-
          pushd charts/aspnet
          mv values-${{ env.environment }}.yaml values.yaml
          ls -al
          popd
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts