name: Helm package and push

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edit values files
        run: |-
          pwd
      - name: Helm package and publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts